/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelos;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author babar
 */
public class JanelaFormulario extends javax.swing.JFrame {
    private final TabelaCliente tabCliente = new TabelaCliente();
    private final List<Cliente> listaDeClientes = new ArrayList();
    private int linhaCliente=-1;
    private final TabelaPedido tabPedido = new TabelaPedido();
    private final List<Pedido> listaDePedidos = new ArrayList();
    private int linhaPedido=-1;
    /**
     * Creates new form NovoJFrame2
     */
    public JanelaFormulario() {
        
        initComponents();
        System.out.println("TESTE");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nomeCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dataCliente = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        emailCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cpfCliente = new JtextFieldSomenteNumeros(11);
        incluirCliente = new java.awt.Button();
        alterarCliente = new java.awt.Button();
        listarCliente = new java.awt.Button();
        excluirCliente = new java.awt.Button();
        limparCliente = new java.awt.Button();
        jSeparator4 = new javax.swing.JSeparator();
        scrollCliente = new javax.swing.JScrollPane();
        tabelaCliente = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        Cliente = new java.awt.Label();
        cpfPedido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nomePedido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sobrenomePedido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pesquisarPedido = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Pedido = new java.awt.Label();
        jLabel4 = new javax.swing.JLabel();
        formaPedido = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        materialPedido = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        alturaPedido = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        larguraPedido = new javax.swing.JTextField();
        incluirPedido = new javax.swing.JButton();
        alterarPedido = new javax.swing.JButton();
        excluirPedido = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        scrollPedido = new javax.swing.JScrollPane();
        tabelaPedido = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        totalPedido = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tamanhoPedido = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        matrialPreco = new javax.swing.JComboBox();
        m2Preco = new javax.swing.JTextField();
        atualizarPreco = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Nome:");

        jLabel6.setText("Data Nascimento:");

        try {
            dataCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setText("E-mail:");

        jLabel8.setText("CPF:");

        incluirCliente.setLabel("Incluir");
        incluirCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                incluirClienteMouseClicked(evt);
            }
        });

        alterarCliente.setLabel("Alterar");
        alterarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alterarClienteMouseClicked(evt);
            }
        });

        listarCliente.setLabel("Listar");
        listarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listarClienteMouseClicked(evt);
            }
        });

        excluirCliente.setLabel("Excluir");
        excluirCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excluirClienteMouseClicked(evt);
            }
        });

        limparCliente.setLabel("Limpar");
        limparCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limparClienteMouseClicked(evt);
            }
        });

        tabelaCliente.setModel(tabCliente);
        tabelaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClienteMouseClicked(evt);
            }
        });
        scrollCliente.setViewportView(tabelaCliente);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(incluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alterarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limparCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailCliente)
                            .addComponent(dataCliente)
                            .addComponent(cpfCliente)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(scrollCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jSeparator4)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dataCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(emailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(incluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(excluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limparCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alterarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cliente", jPanel1);

        Cliente.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Cliente.setText("Cliente");

        jLabel1.setText("CPF do Cliente:");

        nomePedido.setEditable(false);

        jLabel2.setText("Nome:");

        sobrenomePedido.setEditable(false);

        jLabel3.setText("Sobrenome:");

        pesquisarPedido.setText("Pesquisar");
        pesquisarPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesquisarPedidoMouseClicked(evt);
            }
        });

        Pedido.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Pedido.setText("Pedido");

        jLabel4.setText("Forma do Tapete:");

        formaPedido.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Retângulo", "Triângulo", "Círculo" }));
        formaPedido.setToolTipText("Retângulo, Triângulo, Círculo");

        jLabel9.setText("Selecione o Material:");

        materialPedido.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Comum", "Luxo", "Premium" }));
        materialPedido.setToolTipText("");

        jLabel10.setText("Altura (m):");

        alturaPedido.setText("2");

        jLabel11.setText("Largura (m):");

        larguraPedido.setText("2");

        incluirPedido.setText("Incluir ");
        incluirPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                incluirPedidoMouseClicked(evt);
            }
        });

        alterarPedido.setText("Alterar");
        alterarPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alterarPedidoMouseClicked(evt);
            }
        });

        excluirPedido.setText("Excluir");

        tabelaPedido.setModel(tabPedido);
        tabelaPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPedidoMouseClicked(evt);
            }
        });
        scrollPedido.setViewportView(tabelaPedido);

        jLabel14.setText("Total do Pedido:");

        totalPedido.setText("jTextField5");

        jLabel15.setText("Tamanho:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alturaPedido)
                                    .addComponent(larguraPedido)
                                    .addComponent(formaPedido, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(materialPedido, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tamanhoPedido)))
                            .addComponent(scrollPedido)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(396, 396, 396))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cpfPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                                    .addComponent(sobrenomePedido, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomePedido, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(10, 10, 10)
                                .addComponent(pesquisarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(9, 9, 9))
            .addComponent(jSeparator3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(incluirPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alterarPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluirPedido)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pesquisarPedido)
                    .addComponent(cpfPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomePedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sobrenomePedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(formaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(materialPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(alturaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(larguraPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tamanhoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(excluirPedido, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(incluirPedido)
                        .addComponent(alterarPedido)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(jLabel14))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pedido", jPanel2);

        jLabel12.setText("Material:");

        jLabel13.setText("Preço do M2:");

        matrialPreco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        m2Preco.setText("jTextField4");

        atualizarPreco.setText("Atualizar");
        atualizarPreco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atualizarPrecoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(matrialPreco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(m2Preco, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(atualizarPreco)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(matrialPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(m2Preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(atualizarPreco)
                .addContainerGap(504, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Preço Material", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void incluirClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incluirClienteMouseClicked

        try{
        String nome = nomeCliente.getText();
        String email = emailCliente.getText();
        LocalDate dataNascimento = LocalDate.parse(dataCliente.getText(),DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        String cpf = imprimeCPF(cpfCliente.getText());
        Cliente cliente = new Cliente(-1L,nome,email,cpf,dataNascimento);
        listaDeClientes.add(cliente);
        tabCliente.adicionaCliente(cliente);
        }catch(DateTimeParseException e){
            JOptionPane.showMessageDialog(null, "Data de Nascimento Inválida");
        }catch(StringIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "CPF Inválido");
        }      
    }//GEN-LAST:event_incluirClienteMouseClicked

     public static String imprimeCPF(String CPF) {
           return(CPF.substring(0, 3) + "." + CPF.substring(3, 6) + "." +
           CPF.substring(6, 9) + "-" + CPF.substring(9, 11));
        }
     
    public static String limpaCPF(String CPF) {
        CPF = CPF.replaceAll("\\.", "");
        CPF = CPF.replaceAll("-", "");
        return CPF;
     }
     
    private void listarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarClienteMouseClicked
        tabCliente.atualizarTabela(listaDeClientes);
        // TODO add your handling code here:
    }//GEN-LAST:event_listarClienteMouseClicked

    private void limparClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limparClienteMouseClicked
        tabCliente.limpaTabela();
        // TODO add your handling code here:
    }//GEN-LAST:event_limparClienteMouseClicked

    private void alterarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alterarClienteMouseClicked
    
        if(linhaCliente!=-1){
            Cliente cliente = tabCliente.getCliente(linhaCliente);
            if(cliente == null){
                return;
            }
            LocalDate dataNascimento = LocalDate.parse(dataCliente.getText(),DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            cliente.setDataNascimento(dataNascimento);
            cliente.setNome(nomeCliente.getText());
            cliente.setEmail(emailCliente.getText());
            cliente.setCpf(imprimeCPF(cpfCliente.getText()));
            //Atualiza tabela
            tabCliente.fireTableRowsUpdated(linhaCliente, linhaCliente);
            
        }
    }//GEN-LAST:event_alterarClienteMouseClicked

    public String toString(Double var){
        String varD = String.valueOf(var);
        return varD;
    }
    
    private void excluirClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluirClienteMouseClicked
        int[] linhasSelecionadas = tabelaCliente.getSelectedRows();
        List<Cliente> listaExcluir = new ArrayList();
        for (int i = 0; i < linhasSelecionadas.length; i++) {
            Cliente cliente = tabCliente.getCliente(linhasSelecionadas[i]);
            listaExcluir.add(cliente);

        }
        for(Cliente cliente:listaExcluir){
            listaDeClientes.remove(cliente);
            tabCliente.removeCliente(cliente);
        }
    }//GEN-LAST:event_excluirClienteMouseClicked

    private void tabelaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClienteMouseClicked
        //Pega a linha clicada
        linhaCliente = tabelaCliente.rowAtPoint(evt.getPoint());
        //Pega o contato da linha clidada
        Cliente cliente = tabCliente.getCliente(linhaCliente);
        //Seta os dados nos componentes
        nomeCliente.setText(cliente.getNome());
        dataCliente.setText(cliente.getDataNascimento().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        emailCliente.setText(cliente.getEmail());
        cpfCliente.setText(limpaCPF(cliente.getCpf()));
    }//GEN-LAST:event_tabelaClienteMouseClicked

    private void pesquisarPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisarPedidoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarPedidoMouseClicked

    private void incluirPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incluirPedidoMouseClicked
        // TODO add your handling code here:
       
        String forma = formaPedido.getActionCommand();
        String material = materialPedido.getToolTipText();
        String altura = alturaPedido.getText();
        String largura = larguraPedido.getText();
        if(!largura.isEmpty() && !altura.isEmpty()){
         tamanhoPedido.setText(calcularTamanho(altura, largura));
        }
        String tamanho = tamanhoPedido.getText();
        String preco = "50";
  
        Pedido pedido = new Pedido(-1L,forma, material, toDouble(largura), toDouble(altura), toDouble(tamanho), toDouble(preco));
        listaDePedidos.add(pedido);
        tabPedido.adicionaPedido(pedido);
    }//GEN-LAST:event_incluirPedidoMouseClicked

    public String calcularTamanho(String altura, String largura){
        Double alturaD = Double.valueOf(altura);
        Double larguraD = Double.valueOf(largura);
        Double result = (alturaD)*(larguraD);
        String resultStr = String.valueOf(result);
      return resultStr;
    }
    
   public double calcularPreco(Forma forma, Material material){
      return ((forma.calcularArea())*(material.getValor()));
    }
   
   public double toDouble(String string){
       if(string.contains(","))
           string = string.replace(",", ".");
      return Double.valueOf(string);
    }
    
    private void alterarPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alterarPedidoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_alterarPedidoMouseClicked

    private void atualizarPrecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizarPrecoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_atualizarPrecoMouseClicked

    private void tabelaPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPedidoMouseClicked
       //Pega a linha clicada
        linhaPedido = tabelaPedido.rowAtPoint(evt.getPoint());
        //Pega o contato da linha clidada
        Pedido pedido = tabPedido.getCliente(linhaPedido);
        //Seta os dados nos componentes
        formaPedido.setSelectedItem(pedido.getForma());
        materialPedido.setSelectedItem(pedido.getMaterial());
        alturaPedido.setText(toString(pedido.getAltura()));
        larguraPedido.setText(toString(pedido.getLargura()));
        tamanhoPedido.setText(toString(pedido.getTamanho()));
    }//GEN-LAST:event_tabelaPedidoMouseClicked


    public static void main(String args[]) {
        
        /* Cliente */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JanelaFormulario().setVisible(true);
            }
        });
        
        /* Material */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Cliente;
    private java.awt.Label Pedido;
    private java.awt.Button alterarCliente;
    private javax.swing.JButton alterarPedido;
    private javax.swing.JTextField alturaPedido;
    private javax.swing.JButton atualizarPreco;
    private javax.swing.JTextField cpfCliente;
    private javax.swing.JTextField cpfPedido;
    private javax.swing.JFormattedTextField dataCliente;
    private javax.swing.JTextField emailCliente;
    private java.awt.Button excluirCliente;
    private javax.swing.JButton excluirPedido;
    private javax.swing.JComboBox formaPedido;
    private java.awt.Button incluirCliente;
    private javax.swing.JButton incluirPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField larguraPedido;
    private java.awt.Button limparCliente;
    private java.awt.Button listarCliente;
    private javax.swing.JTextField m2Preco;
    private javax.swing.JComboBox materialPedido;
    private javax.swing.JComboBox matrialPreco;
    private javax.swing.JTextField nomeCliente;
    private javax.swing.JTextField nomePedido;
    private javax.swing.JButton pesquisarPedido;
    private javax.swing.JScrollPane scrollCliente;
    private javax.swing.JScrollPane scrollPedido;
    private javax.swing.JTextField sobrenomePedido;
    private javax.swing.JTable tabelaCliente;
    private javax.swing.JTable tabelaPedido;
    private javax.swing.JTextField tamanhoPedido;
    private javax.swing.JTextField totalPedido;
    // End of variables declaration//GEN-END:variables
}
