/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelos;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author babar
 */
public class JanelaFormulario extends javax.swing.JFrame {
    private final TabelaCliente tabCliente = new TabelaCliente();
    private final List<Cliente> listaDeClientes = new ArrayList();
    private int linhaCliente=-1;
    private final TabelaPedido tabPedido = new TabelaPedido();
    private final List<Pedido> listaDePedidos = new ArrayList();
    private List<Pedido> clientePedido = new ArrayList();;
    private int linhaPedido=-1;
    private final List<Material> materiais = new ArrayList();
    private final Util util = new Util();
    private Cliente clienteSelecionado;
    

    /**
     * Creates new form NovoJFrame2
     */
    public JanelaFormulario() {
  
        initComponents();
        util.popularMateriais(materiais);
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nomeCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dataCliente = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        emailCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cpfCliente = new JtextFieldSomenteNumeros(11);
        jSeparator4 = new javax.swing.JSeparator();
        scrollCliente = new javax.swing.JScrollPane();
        tabelaCliente = new javax.swing.JTable();
        incluirCliente = new javax.swing.JButton();
        alterarCliente = new javax.swing.JButton();
        excluirCliente = new javax.swing.JButton();
        listarCliente = new javax.swing.JButton();
        limparCliente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Cliente = new java.awt.Label();
        cpfPedido = new JtextFieldSomenteNumeros(11);
        jLabel1 = new javax.swing.JLabel();
        nomePedido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sobrenomePedido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pesquisarPedido = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Pedido = new java.awt.Label();
        jLabel4 = new javax.swing.JLabel();
        formaPedido = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        materialPedido = new javax.swing.JComboBox();
        alturaPedido = new JtextFieldSomenteNumPonto(10);
        larguraPedido = new JtextFieldSomenteNumPonto(10);
        incluirPedido = new javax.swing.JButton();
        alterarPedido = new javax.swing.JButton();
        excluirPedido = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        scrollPedido = new javax.swing.JScrollPane();
        tabelaPedido = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        totalPedido = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tamanhoPedido = new JtextFieldSomenteNumPonto(10);
        text1 = new javax.swing.JTextField();
        text2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        materialPreco = new javax.swing.JComboBox();
        m2Preco = new javax.swing.JTextField();
        atualizarPreco = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(153, 153, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel5.setText("Nome:");

        jLabel6.setText("Data Nascimento:");

        try {
            dataCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setText("E-mail:");

        jLabel8.setText("CPF:");

        tabelaCliente.setModel(tabCliente);
        tabelaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClienteMouseClicked(evt);
            }
        });
        scrollCliente.setViewportView(tabelaCliente);

        incluirCliente.setText("Incluir");
        incluirCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                incluirClienteMouseClicked(evt);
            }
        });

        alterarCliente.setText("Alterar");
        alterarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alterarClienteMouseClicked(evt);
            }
        });

        excluirCliente.setText("Excluir");
        excluirCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excluirClienteMouseClicked(evt);
            }
        });

        listarCliente.setText("Listar");
        listarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listarClienteMouseClicked(evt);
            }
        });

        limparCliente.setText("Limpar");
        limparCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limparClienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailCliente)
                            .addComponent(dataCliente)
                            .addComponent(cpfCliente)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(scrollCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(incluirCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alterarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluirCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limparCliente)))
                .addContainerGap())
            .addComponent(jSeparator4)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dataCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(emailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(incluirCliente)
                    .addComponent(alterarCliente)
                    .addComponent(excluirCliente)
                    .addComponent(listarCliente)
                    .addComponent(limparCliente))
                .addGap(11, 11, 11)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cliente", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        Cliente.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Cliente.setText("Cliente");

        jLabel1.setText("CPF do Cliente:");

        nomePedido.setEditable(false);

        jLabel2.setText("Nome:");

        sobrenomePedido.setEditable(false);

        jLabel3.setText("Sobrenome:");

        pesquisarPedido.setText("Pesquisar");
        pesquisarPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesquisarPedidoMouseClicked(evt);
            }
        });

        Pedido.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Pedido.setText("Pedido");

        jLabel4.setText("Forma do Tapete:");

        formaPedido.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Retangular", "Circular", "Triangular" }));
        formaPedido.setToolTipText("");
        formaPedido.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                formaPedidoItemStateChanged(evt);
            }
        });

        jLabel9.setText("Selecione o Material:");

        materialPedido.setModel(new GenericComboModel<Material>(materiais));
        materialPedido.setToolTipText("");

        alturaPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alturaPedidoMouseClicked(evt);
            }
        });
        alturaPedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                alturaPedidoKeyReleased(evt);
            }
        });

        larguraPedido.setToolTipText("");
        larguraPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                larguraPedidoMouseClicked(evt);
            }
        });
        larguraPedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                larguraPedidoKeyReleased(evt);
            }
        });

        incluirPedido.setText("Incluir ");
        incluirPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                incluirPedidoMouseClicked(evt);
            }
        });

        alterarPedido.setText("Alterar");
        alterarPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alterarPedidoMouseClicked(evt);
            }
        });

        excluirPedido.setText("Excluir");
        excluirPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excluirPedidoMouseClicked(evt);
            }
        });

        tabelaPedido.setModel(tabPedido);
        tabelaPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPedidoMouseClicked(evt);
            }
        });
        scrollPedido.setViewportView(tabelaPedido);

        jLabel14.setText("Total do Pedido:");

        totalPedido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel15.setText("Tamanho (m²)");

        tamanhoPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tamanhoPedidoMouseClicked(evt);
            }
        });
        tamanhoPedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tamanhoPedidoKeyReleased(evt);
            }
        });

        text1.setEditable(false);
        text1.setBackground(new java.awt.Color(204, 204, 255));
        text1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        text1.setText("Altura (m):");
        text1.setBorder(null);

        text2.setEditable(false);
        text2.setBackground(new java.awt.Color(204, 204, 255));
        text2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        text2.setText("Largura (m):");
        text2.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4)
                            .addComponent(jLabel15)
                            .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(alturaPedido)
                            .addComponent(larguraPedido)
                            .addComponent(formaPedido, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(materialPedido, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tamanhoPedido)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cpfPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                                    .addComponent(sobrenomePedido, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomePedido, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(10, 10, 10)
                                .addComponent(pesquisarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(9, 9, 9))
            .addComponent(jSeparator3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(incluirPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alterarPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluirPedido)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pesquisarPedido)
                    .addComponent(cpfPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomePedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sobrenomePedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(formaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(materialPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alturaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(larguraPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tamanhoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(excluirPedido, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(incluirPedido)
                        .addComponent(alterarPedido)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(jLabel14))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pedido", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel12.setText("Material:");

        jLabel13.setText("Preço do M2:");

        materialPreco.setModel(new GenericComboModel<Material>(materiais));
        materialPreco.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                materialPrecoItemStateChanged(evt);
            }
        });

        m2Preco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m2PrecoMouseClicked(evt);
            }
        });

        atualizarPreco.setText("Atualizar");
        atualizarPreco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atualizarPrecoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(materialPreco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(m2Preco, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(atualizarPreco)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(materialPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(m2Preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(atualizarPreco)
                .addContainerGap(504, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Preço Material", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
         
    private void tabelaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClienteMouseClicked
        //Pega a linha clicada
        linhaCliente = tabelaCliente.rowAtPoint(evt.getPoint());
        //Pega o contato da linha clidada
        Cliente cliente = tabCliente.getCliente(linhaCliente);
        //Seta os dados nos componentes
        nomeCliente.setText(cliente.getNome());
        dataCliente.setText(cliente.getDataNascimento().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        emailCliente.setText(cliente.getEmail());
        cpfCliente.setText(util.limpaCPF(cliente.getCpf()));
    }//GEN-LAST:event_tabelaClienteMouseClicked

    private void pesquisarPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisarPedidoMouseClicked
        try{
        String cpf = cpfPedido.getText();
        Cliente cliente = util.buscarCliente(listaDeClientes, cpf);
        clientePedido = new ArrayList();
        listaDePedidos.clear();
            if(cliente != null){
                clienteSelecionado = cliente;
                String nomeCompleto = clienteSelecionado.getNome();
                List<Pedido> pedidosCliente = clienteSelecionado.getPedidos();
                if(pedidosCliente != null){
                        clientePedido = pedidosCliente;
                        listaDePedidos.addAll(pedidosCliente);
                        tabPedido.atualizarTabela(listaDePedidos);
                        totalPedido.setText(tabPedido.atualizaPreco());                     
                }else{
                    tabPedido.atualizarTabela(listaDePedidos);
                    totalPedido.setText(tabPedido.atualizaPreco());
                }
                if(nomeCompleto.contains(" ")){
                    String nome = nomeCompleto.substring(0, nomeCompleto.indexOf(" "));
                    String sobrenome = nomeCompleto.substring(nomeCompleto.indexOf(" ")+1);
                    nomePedido.setText(nome);
                    sobrenomePedido.setText(sobrenome);
                }else{
                    nomePedido.setText(nomeCompleto);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Cliente não cadastrado!");
                nomePedido.setText("");
                sobrenomePedido.setText("");
                totalPedido.setText("R$ 0,00");
                clienteSelecionado = null;
                tabPedido.limpaTabela();
            }
       }catch(StringIndexOutOfBoundsException e){
           JOptionPane.showMessageDialog(null, "Cliente não cadastrado!");
           tabPedido.limpaTabela();
       }
    }//GEN-LAST:event_pesquisarPedidoMouseClicked

    private void incluirPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incluirPedidoMouseClicked
        try{
            Material pSelected = (Material) materialPedido.getSelectedItem();
            String forma = String.valueOf(formaPedido.getSelectedItem());
            String altura = alturaPedido.getText().replace("m", "");
            String largura = larguraPedido.getText().replace("m", "");
            String tamanho = tamanhoPedido.getText().replace("m²", "");
            BigDecimal preco = util.calcularPreco(tamanho, pSelected);

            Pedido pedido = new Pedido(-1L,forma, pSelected, util.toDouble(largura), 
            util.toDouble(altura), util.toDouble(tamanho), preco);
            
            clientePedido.add(pedido);
            clienteSelecionado.setPedidos(clientePedido);
            listaDePedidos.add(pedido);
            tabPedido.adicionaPedido(pedido);      
            totalPedido.setText(tabPedido.atualizaPreco());
            
        }catch(NullPointerException e){
             JOptionPane.showMessageDialog(null, "Cliente não encontrado!");
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Campos não preenchidos");
        }
    }//GEN-LAST:event_incluirPedidoMouseClicked
       
    private void alterarPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alterarPedidoMouseClicked
       if(linhaPedido!=-1){
           try{
            Pedido pedido = tabPedido.getPedido(linhaPedido);
            if(pedido == null){
                return;
            }
            Material pSelected = (Material) materialPedido.getSelectedItem();
            pedido.setForma(String.valueOf(formaPedido.getSelectedItem()));
            pedido.setMaterial(pSelected);
            pedido.setLargura(util.toDouble(larguraPedido.getText().replace("m", "")));
            pedido.setAltura(util.toDouble(alturaPedido.getText().replace("m", "")));
            pedido.setTamanho(util.toDouble(tamanhoPedido.getText().replace("m²", "")));
            
            BigDecimal preco = util.calcularPreco(tamanhoPedido.getText().replace("m²", ""), pSelected);
            pedido.setPreco(preco);
            //Atualiza tabela
            tabPedido.fireTableRowsUpdated(linhaPedido, linhaPedido);
            totalPedido.setText(tabPedido.atualizaPreco());
            
           }catch(NullPointerException e){
                JOptionPane.showMessageDialog(null, "Campos não preenchidos");
           }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Campos não preenchidos");
           }catch(IndexOutOfBoundsException e){
               JOptionPane.showMessageDialog(null, "Não é possivel alterar!");
           }
        }
    }//GEN-LAST:event_alterarPedidoMouseClicked

    private void atualizarPrecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizarPrecoMouseClicked
        try{
            Material pSelected = (Material) materialPreco.getSelectedItem();
            String preco = m2Preco.getText().replace(".", "");
            preco = preco.replace(",", ".");
            preco = preco.replace("R$ ", "");
            pSelected.setValor(new BigDecimal(preco));
            m2Preco.setText(util.formatarReais(pSelected.getValor()));
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Valor inválido!");
        }
    }//GEN-LAST:event_atualizarPrecoMouseClicked

    private void tabelaPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPedidoMouseClicked
       //Pega a linha clicada
        linhaPedido = tabelaPedido.rowAtPoint(evt.getPoint());
        //Pega o contato da linha clidada
        Pedido pedido = tabPedido.getPedido(linhaPedido);
        //Seta os dados nos componentes
        formaPedido.setSelectedItem(pedido.getForma());
        materialPedido.setSelectedItem(pedido.getMaterial());
        alturaPedido.setText(util.toString(pedido.getAltura())+"m");
        larguraPedido.setText(util.toString(pedido.getLargura())+"m");
        tamanhoPedido.setText(util.toString(pedido.getTamanho())+"m²");
    }//GEN-LAST:event_tabelaPedidoMouseClicked

    private void excluirPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluirPedidoMouseClicked
        try{
            int[] linhasSelecionadas = tabelaPedido.getSelectedRows();
            List<Pedido> listaExcluir = new ArrayList();

            for (int i = 0; i < linhasSelecionadas.length; i++) {
                Pedido pedido = tabPedido.getPedido(linhasSelecionadas[i]);
                listaExcluir.add(pedido);

            }
            for(Pedido pedido : listaExcluir){
                clientePedido.remove(pedido);
                listaDePedidos.remove(pedido);
                tabPedido.removePedido(pedido);
            }

            clienteSelecionado.setPedidos(clientePedido);

            totalPedido.setText(tabPedido.atualizaPreco());
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Não é possível excluir!");
        }
    }//GEN-LAST:event_excluirPedidoMouseClicked

    private void materialPrecoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_materialPrecoItemStateChanged
        Material pSelected = (Material)materialPreco.getSelectedItem();
        String valorStr = util.formatarReais(pSelected.getValor());
        m2Preco.setText(valorStr);
    }//GEN-LAST:event_materialPrecoItemStateChanged

    private void tamanhoPedidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tamanhoPedidoKeyReleased
        String tamanho = tamanhoPedido.getText().replace("m²", ""); 
        String forma = String.valueOf(formaPedido.getSelectedItem());
        Double tamanhoD = util.tamanhoAltLarg(tamanho, forma);
        larguraPedido.setText(tamanhoD+"m");
        if(!forma.equals("Circular")){
            alturaPedido.setText(tamanhoD+"m");
        }
    }//GEN-LAST:event_tamanhoPedidoKeyReleased

    private void larguraPedidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_larguraPedidoKeyReleased
        String altura = alturaPedido.getText().replace("m", "");
        String largura = larguraPedido.getText().replace("m", "");    
        String forma = String.valueOf(formaPedido.getSelectedItem());
        Double valor = util.calcularTamanho(altura, largura, forma);
        tamanhoPedido.setText(valor+ "m²");
    }//GEN-LAST:event_larguraPedidoKeyReleased

    private void alturaPedidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alturaPedidoKeyReleased
        String altura = alturaPedido.getText().replace("m", "");
        String largura = larguraPedido.getText().replace("m", "");    
        String forma = String.valueOf(formaPedido.getSelectedItem());
        Double valor = util.calcularTamanho(altura, largura, forma);
        tamanhoPedido.setText(valor+ "m²");
    }//GEN-LAST:event_alturaPedidoKeyReleased

    private void tamanhoPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tamanhoPedidoMouseClicked
        String tamanho = tamanhoPedido.getText();
        tamanho = tamanho.replace("m²", "");
        tamanhoPedido.setText(tamanho);
    }//GEN-LAST:event_tamanhoPedidoMouseClicked

    private void alturaPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alturaPedidoMouseClicked
        String altura = alturaPedido.getText();
        altura = altura.replace("m", "");
        alturaPedido.setText(altura);
    }//GEN-LAST:event_alturaPedidoMouseClicked

    private void larguraPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_larguraPedidoMouseClicked
        String largura = larguraPedido.getText();
        largura = largura.replace("m", "");
        larguraPedido.setText(largura);
    }//GEN-LAST:event_larguraPedidoMouseClicked

    private void formaPedidoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_formaPedidoItemStateChanged
        String forma =  String.valueOf(formaPedido.getSelectedItem());
            if(forma.equals("Retangular")){
                text1.setText("Altura (m):");
                text2.setText("Largura (m):");
                alturaPedido.setEditable(true);
                alturaPedido.setEnabled(true);
            }if(forma.equals("Circular")){
                text1.setText("");
                text2.setText("Raio:");
                alturaPedido.setText("0");
                alturaPedido.setEditable(false);
                alturaPedido.setEnabled(false);
            }if(forma.equals("Triangular")){
                text1.setText("Altura (m):");
                text2.setText("Base (m):");            
                alturaPedido.setEditable(true);
                alturaPedido.setEnabled(true);
            }
        String altura = alturaPedido.getText().replace("m", "");
        String largura = larguraPedido.getText().replace("m", "");   
        Double valor = util.calcularTamanho(altura, largura, forma);
        tamanhoPedido.setText(valor+ "m²");
    }//GEN-LAST:event_formaPedidoItemStateChanged

    private void m2PrecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m2PrecoMouseClicked
        String preco = m2Preco.getText();
        preco = preco.replace("R$ ", "");
        m2Preco.setText(preco);
    }//GEN-LAST:event_m2PrecoMouseClicked

    private void incluirClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incluirClienteMouseClicked
    Boolean consulta = util.cpfRepetido(listaDeClientes, cpfCliente.getText());
        if(consulta){
            JOptionPane.showMessageDialog(null, "CPF já cadastrado!");
        }else{
            try{
                String nome = nomeCliente.getText();
                if(nome.isEmpty() || nome == null){
                    JOptionPane.showMessageDialog(null, "Nome é Obrigatório!");
                    return;
                }if(!nome.contains(" ")){
                    JOptionPane.showMessageDialog(null, "Digite o Nome Completo!");
                    return;
                }
                String email = emailCliente.getText();
                LocalDate dataNascimento = LocalDate.parse(dataCliente.getText(),DateTimeFormatter.ofPattern("dd/MM/yyyy"));
                String cpf = util.imprimeCPF(cpfCliente.getText());
                Cliente cliente = new Cliente(-1L,nome,email,cpf,dataNascimento);
                listaDeClientes.add(cliente);
                tabCliente.adicionaCliente(cliente);
            }catch(DateTimeParseException e){
                JOptionPane.showMessageDialog(null, "Data de Nascimento Inválida");
            }catch(StringIndexOutOfBoundsException e){
                JOptionPane.showMessageDialog(null, "CPF Inválido");
            } 
        }
    }//GEN-LAST:event_incluirClienteMouseClicked

    private void alterarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alterarClienteMouseClicked
        if(linhaCliente!=-1){
            Cliente cliente = tabCliente.getCliente(linhaCliente);
            if(cliente == null){
                return;
            }
            LocalDate dataNascimento = LocalDate.parse(dataCliente.getText(),DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            cliente.setDataNascimento(dataNascimento);
            cliente.setNome(nomeCliente.getText());
            cliente.setEmail(emailCliente.getText());
            cliente.setCpf(util.imprimeCPF(cpfCliente.getText()));
            //Atualiza tabela
            tabCliente.fireTableRowsUpdated(linhaCliente, linhaCliente);
            
        }
    }//GEN-LAST:event_alterarClienteMouseClicked

    private void excluirClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluirClienteMouseClicked
        int[] linhasSelecionadas = tabelaCliente.getSelectedRows();
        List<Cliente> listaExcluir = new ArrayList();
        for (int i = 0; i < linhasSelecionadas.length; i++) {
            Cliente cliente = tabCliente.getCliente(linhasSelecionadas[i]);
            listaExcluir.add(cliente);

        }
        for(Cliente cliente:listaExcluir){
            listaDeClientes.remove(cliente);
            tabCliente.removeCliente(cliente);
        }
    }//GEN-LAST:event_excluirClienteMouseClicked

    private void listarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarClienteMouseClicked
        tabCliente.atualizarTabela(listaDeClientes);
    }//GEN-LAST:event_listarClienteMouseClicked

    private void limparClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limparClienteMouseClicked
        tabCliente.limpaTabela();
    }//GEN-LAST:event_limparClienteMouseClicked


    public static void main(String args[]) {
        
        /* Cliente */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               JanelaFormulario jan = new JanelaFormulario();
               jan.setVisible(true);
               jan.setSize(620, 710);
               jan.setTitle("Venda de Tapetes");
               jan.setResizable(false);
               jan.setLocationRelativeTo(null);
            }
        });
        
        /* Material */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Cliente;
    private java.awt.Label Pedido;
    private javax.swing.JButton alterarCliente;
    private javax.swing.JButton alterarPedido;
    private javax.swing.JTextField alturaPedido;
    private javax.swing.JButton atualizarPreco;
    private javax.swing.JTextField cpfCliente;
    private javax.swing.JTextField cpfPedido;
    private javax.swing.JFormattedTextField dataCliente;
    private javax.swing.JTextField emailCliente;
    private javax.swing.JButton excluirCliente;
    private javax.swing.JButton excluirPedido;
    private javax.swing.JComboBox formaPedido;
    private javax.swing.JButton incluirCliente;
    private javax.swing.JButton incluirPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField larguraPedido;
    private javax.swing.JButton limparCliente;
    private javax.swing.JButton listarCliente;
    private javax.swing.JTextField m2Preco;
    private javax.swing.JComboBox materialPedido;
    private javax.swing.JComboBox materialPreco;
    private javax.swing.JTextField nomeCliente;
    private javax.swing.JTextField nomePedido;
    private javax.swing.JButton pesquisarPedido;
    private javax.swing.JScrollPane scrollCliente;
    private javax.swing.JScrollPane scrollPedido;
    private javax.swing.JTextField sobrenomePedido;
    private javax.swing.JTable tabelaCliente;
    private javax.swing.JTable tabelaPedido;
    private javax.swing.JTextField tamanhoPedido;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text2;
    private javax.swing.JTextField totalPedido;
    // End of variables declaration//GEN-END:variables
}
